name: CI
on:  
  push:
    tags:
      - 'v*'

jobs:
  oraclecloud:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 8G \
              --repositories-file oracle/repositories \
              --packages "$(cat oracle/packages)" \
              --script-chroot \
              alpine-oraclecloud-$(date +%Y-%m-%d).qcow2 -- ./oracle/configure.sh

      - name: Compress image
        run: tar -czvf alpine-oraclecloud-$(date +%Y-%m-%d).tar.gz alpine-oraclecloud-$(date +%Y-%m-%d).qcow2
    
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "alpine-oraclecloud-$(date +%Y-%m-%d).tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}